# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('topic', models.CharField(max_length=20)),
                ('content_file', models.FileField(upload_to='blogposts%Y/')),
            ],
        ),
    ]
